### ISSUE TITLE
[Bug] New file open in top sidebar folder

### ISSUE THREAD

**Issue by Kristinita** [math2001/FileManager#14] opened 2017-03-27 15:00 UTC
### 1. Summary

I can to create file via File Manager in top folder of my sidebar, but not in current folder. [**Some features into GIFs**](https://github.com/math2001/FileManager/tree/master/docs/imgs) don't work for me.

### 2. Settings

My sidebar:

![Sidebar](http://i.imgur.com/SZC8jZp.png)

+ `Киролайна `— top folder of my sidebar,
+ `KristinitaLuckyLink/KristinitaLuckyLink.py` — opened file.

### 3. Steps to reproduce

I reproduce the problem in a version of Sublime Text without plugins and user settings.

I install File Manager → I restart Sublime Text → I open file `KristinitaLuckyLink.py` → <kbd>Ctrl+Shift+P</kbd> → `File Manager: New File`.

### 4. Expected behavior

Create file in current folder.

### 5. Actual behavior

See image in 2 section. I create file in top folder, not current.

### 6. Environment

**Operating system and version:**
Windows 10 Enterprise LTSB 64-bit EN
**Sublime Text:**
Build 3126

Thanks.

**Comment by math2001** [comment] 2017-03-29 00:53
This is not a bug. I've never had the idea of doing this, it is just a coincidence in a GIF as you said (could you let me know which one is it?).

It is a good idea, though, I'll add this on the todo. 👍

**Comment by math2001** [comment] 2020-01-04 10:37
Oh wait, I've done this, see details here: https://github.com/math2001/FileManager/issues/16#issuecomment-308361859. Maybe there should be an example somewhere in the docs though. I'll close this anyway :slightly_smiling_face:

**Closed by math2001** 2020-01-04 10:37 UTC
Labels: enhancement
