### ISSUE TITLE
fm_create_file_from_selection AttributeError

### ISSUE THREAD

**Issue by unknownuser88** [math2001/FileManager#10] opened 2017-03-07 15:24 UTC
```
File "FMcommands.create_from_selection in /home/username/.config/sublime-text-3/Installed Packages/FileManager.sublime-package", line 34, in run
File "pathhelper in /home/username/.config/sublime-text-3/Installed Packages/FileManager.sublime-package", line 14, in computer_friendly
AttributeError: 'NoneType' object has no attribute 'path'
```

Also get this on right click on selection

```
File "FMcommands.appcommand in /home/username/.config/sublime-text-3/Installed Packages/FileManager.sublime-package", line 9, in is_visible
File "sublimefunctions in /home/username/.config/sublime-text-3/Installed Packages/FileManager.sublime-package", line 24, in get_settings
AttributeError: 'NoneType' object has no attribute 'load_settings'
```

**Comment by unknownuser88** [comment] 2017-03-07 16:16
also see some strange big item in context menu
![b1](https://cloud.githubusercontent.com/assets/2427559/23665736/b6fe5cda-0372-11e7-8cda-b34af009c4b6.jpg)

**Comment by math2001** [comment] 2017-03-08 06:06
Ok, let's do one problem at a time.

## First one

It might be because the Sublime Text 3's version of python is prior to `3.4` ([more info](http://stackoverflow.com/questions/29107470/imported-modules-becomes-none-when-replacing-current-module-in-sys-modules-using)), although it's weird since I'm not using any class... I'll have to think about it. 

Can you give me more info about how you got that? do you have this error every time you use this command? Could you try [revert to a fresh state](https://gist.github.com/math2001/04186bb2273fa5accc04f88e44275d49) and install only FileManager and check if you have the same error?

## Second one

Please raise another issue with details (how to get that).

Thanks for your time anyway 👍

**Comment by unknownuser88** [comment] 2017-03-08 09:10
I reset my sublime text install only package control and FileManager 
sublime version: 3126 
python version: 3.5.2

when I open existing file all works file 
but when I press ctrl+n (create new file) then set syntax to javascript then paste some code and select some part and press right click I get the following error

Traceback (most recent call last):
  File "/sublime_text_3/sublime_plugin.py", line 755, in description_
    return self.description(**args)
  File "FMcommands.create_from_selection in /home/username/.config/sublime-text-3/Installed Packages/FileManager.sublime-package", line 117, in description
  File "FMcommands.create_from_selection in /home/username/.config/sublime-text-3/Installed Packages/FileManager.sublime-package", line 114, in get_path
  File "./python3.3/posixpath.py", line 151, in dirname
AttributeError: 'NoneType' object has no attribute 'rfind'

**Comment by math2001** [comment] 2017-03-08 21:40
I see the problem, but there's something that I'm still missing...

The problem is that you're file isn't saved. Yet, to create a file you need the file_name because the url is relative to it.

What I don't understand is how you're able to call it, since if the file isn't saved (`view.file_name()` is `None`), the option isn't displayed.

Note 1: Sublime Text has it's own version of Python (and I which it was at least python 3.5, but anyway), as you can see in the traceback (`File "./python3.3/posixpath.py", line 151, in dirname`).

Note 2: could you install PackageResourceViewer and extract FileManager, you'll get better traceback, which will help me find the problem quicker 🙂 

Thanks for your time again, I really appreciate it! 👍

**Comment by math2001** [comment] 2017-03-08 21:45
I see the problem, but there's something that I'm still missing...

The problem is that you're file isn't saved. Yet, to create a file you need the file_name because the url is relative to it.

What I don't understand is how you're able to call it, since if the file isn't saved (`view.file_name()` is `None`), the option isn't displayed.

Note 1: Sublime Text has it's own version of Python (and I which it was at least python 3.5, but anyway), as you can see in the traceback (`File "./python3.3/posixpath.py", line 151, in dirname`).

Note 2: could you install PackageResourceViewer and extract FileManager, you'll get better traceback, which will help me find the problem quicker 🙂 

Thanks for your time again, I really appreciate it! 👍

**Comment by unknownuser88** [comment] 2017-03-09 10:00
![ezgif com-video-to-gif 2](https://cloud.githubusercontent.com/assets/2427559/23744923/a196a3a8-04cf-11e7-8802-e34af0d46cc8.gif)

I try PackageResourceViewer but after extracting it gives me the same error as I mention bellow

```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 755, in description_
    return self.description(**args)
  File "FMcommands.create_from_selection in /home/username/.config/sublime-text-3/Installed Packages/FileManager.sublime-package", line 117, in description
  File "FMcommands.create_from_selection in /home/username/.config/sublime-text-3/Installed Packages/FileManager.sublime-package", line 114, in get_path
  File "./python3.3/posixpath.py", line 151, in dirname
AttributeError: 'NoneType' object has no attribute 'rfind'
```

I think python 3.3 comes from here

![screenshot from 2017-03-09 13-54-09](https://cloud.githubusercontent.com/assets/2427559/23745160/a7cc00be-04d0-11e7-8dfc-d30dad66d879.png)

**Comment by math2001** [comment] 2017-03-09 21:31
Did you extracted `FileManager`? You should be able to find it under `Packages` (Preference → Browse Packages)

When you have your unsaved file opened, could you paste `print(view.file_name())` in the console and tell me what you get? (you should get `None`)

**Comment by unknownuser88** [comment] 2017-03-10 16:37
Yes I extract FileManager and it put files to `.config/sublime-text-3/Packages` but I didn't see any other output

```
>>> print(view.file_name()) 
None
```

**Comment by math2001** [comment] 2020-01-04 10:20
I'm guessing that was a problem with the `is_visible` method on the command. There's a manual check now, and I can't reproduce this. So, I'm going to close this. Feel free to reopen if that is still happening to you :slightly_smiling_face: 

https://github.com/math2001/FileManager/blob/5984505573e409bcb16b023d208d54a4328025ca/FMcommands/create_from_selection.py#L138

**Closed by math2001** 2020-01-04 10:20 UTC
